version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: basic_api_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-basicapi}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Uncomment to add initialization scripts
      # - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - basic_api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-basicapi}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  basic_api_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
